### PR TITLE
moves phpunit/phpunit from'required' to 'required-dev'

### PR DESCRIPTION
**Pull request by BBrunekreeft**
Should solve #67

### CODE REVIEW

**Review by WyriHaximus — CHANGES_REQUESTED** [review]
Yes sorry @BBrunekreeft I missed that! Could you include the `composer.lock` changes? Can be done with a `composer update --lock -W`

**Comment by BBrunekreeft** [comment]
The lock file already seems fine:

            "require": {
                "php": "^7.1 || ^8.0"
            },
            "replace": {
                "myclabs/deep-copy": "self.version"
            },
            "require-dev": {
                "doctrine/collections": "^1.0",
                "doctrine/common": "^2.6",
                "phpunit/phpunit": "^7.1"
            },

**Comment by BBrunekreeft** [comment]
The composer.lock file has the php-unit requirement already under requirre-dev: 

            "require": {
                "php": "^7.1 || ^8.0"
            },
            "require-dev": {
                "doctrine/coding-standard": "^8.0",
                "ext-pdo": "*",
                "ext-phar": "*",
                "phpbench/phpbench": "^0.13 || 1.0.0-alpha2",
                "phpstan/phpstan": "^0.12",
                "phpstan/phpstan-phpunit": "^0.12",
                "phpunit/phpunit": "^7.0 || ^8.0 || ^9.0"
            },

**Comment by WyriHaximus** [comment]
Yes, but the content hash differs so composer refuses to install it on CI

**Comment by BBrunekreeft** [comment]
Solved the hash difference.
But now another test fails. Don't know what that is.

**Comment by WyriHaximus** [comment]
> Solved the hash difference.

Awesome!

> But now another test fails. Don't know what that is.

Right it seems I need to pull this into another package to fully solve this: https://github.com/WyriHaximus/php-compress/blob/master/src/AbstractCompressorTest.php

> But now another test fails. Don't know what that is.

So, in short, the test that fails ensures that you have the required dependencies for all systems you use in your package.

**Review by WyriHaximus — APPROVED** [review]
Include the things I mentioned in the other comment this now looks good. I'll do the split tomorrow and get a release out for this package as well.

**Pull request merged**
